const nome = "Lilly Bloom";
let idade = 16;
const curso = "Ballet e DvS";
const matriculado = true;
console.log(nome);
console.log(idade);
console.log(curso);
console.log(matriculado);
console.log("Nome:", nome);
console.log("Idade:", idade);
console.log("Curso:", curso);
console.log("Está matriculado?", matriculado);